### ISSUE TITLE
Tab to JSON converter fails on parsing Affiliations

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#12]
test_isa_v1_parser.py on feat/reader branch throws up an exception:
```
Error
Traceback (most recent call last):
  File "/Users/dj/PycharmProjects/isa-api/tests/test_isa_v1_parser.py", line 166, in test_jsonToIsatab_writer
    mywriter.parsingJson(self._json_dir, output_dir)
  File "/Users/dj/PycharmProjects/isa-api/isatools/io/json_to_isatab.py", line 78, in parsingJson
    self.writeJsonInvestigationToIsatab(i_filenames, output_dir)
  File "/Users/dj/PycharmProjects/isa-api/isatools/io/json_to_isatab.py", line 96, in writeJsonInvestigationToIsatab
    investigation_str = self.processInvestigationJson(jsonData)
  File "/Users/dj/PycharmProjects/isa-api/isatools/io/json_to_isatab.py", line 129, in processInvestigationJson
    my_str = self.writeSectionInvestigation(my_str, "INVESTIGATION CONTACTS", jsonData["investigation"]["investigationContacts"], self._isatab_i_investigation_contacts_sec)
  File "/Users/dj/PycharmProjects/isa-api/isatools/io/json_to_isatab.py", line 159, in writeSectionInvestigation
    my_str = my_str + "\"" + b[self.commonFunctions.makeAttributeName(i)] + "\"" + "\t"
KeyError: 'investigationPersonAffiliation'
```
This seems to be caused by the json_to_isatab.py JsonToIsatabWriter() class converter being unable to handle looking up investigationPersonAffiliation in ISA-JSON.

**Comment by djcomlab** [comment]
Fixed in previous commits.
