### ISSUE TITLE
isatools pip3.5 install has naming collision with mzml2isa

### ISSUE THREAD

**Issue by podonnellalidyne** [ISA-tools/isa-api#351]
We recently installed isatools using pip3.5.  We are trying to run the isatools/convert/json2isa.py script to regenerate the isatab files from our stored json.  When running this script we get a name collision with trying to import the mzml2isa package since there is already a script named isatool/convert/mzml2isa.py . Here is the error output:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/isatools/convert/json2isatab.py", line 6, in <module>
    from isatools import isajson
  File "/usr/local/lib/python3.5/site-packages/isatools/__init__.py", line 14, in <module>
    from isatools.convert import mzml2isa as mzml2isa_module
  File "/usr/local/lib/python3.5/site-packages/isatools/convert/mzml2isa.py", line 3, in <module>
    from mzml2isa.parsing import convert as mzml_convert
  File "/usr/local/lib/python3.5/site-packages/isatools/convert/mzml2isa.py", line 3, in <module>
    from mzml2isa.parsing import convert as mzml_convert
ImportError: No module named 'mzml2isa.parsing'; 'mzml2isa' is not a package

```
We are going to try and rename the isatool/convert/mzml2isa.py script to avoid this collision and update its references.

**Comment by proccaserra** [comment]
refactoring `mzml2isa.py` to `mzml2isatab.py`
