### ISSUE TITLE
node error while writing study files

### ISSUE THREAD

**Issue by cbaakman** [ISA-tools/isa-api#364]
When I run the following:

```
from isatools.model import (Investigation, Study, Assay, Person, Material,
                            DataFile, plink,
                            OntologySource, OntologyAnnotation, Sample,
                            Source, Characteristic, Protocol, Process)
from isatools import isatab

investigation = Investigation()
investigation.identifier = "PERISCOPE"
investigation.title = "PERtussIS COrrelates of Protection Europe"
investigation.description = """Investigates Bordatela pertussis infection and aims to accelerate the development of new vaccines"""

bert = Study(filename="s_bert.txt")
investigation.studies.append(bert)
bert.identifier = "BERT"
bert.title = "Booster Against Pertussis"
bert.description = """The BERT Booster against pertussis (whooping cough) study investigates
long-term protection against pertussis by giving a repeated vaccination against pertussis."""

hcm = Study(filename="s_hcm.txt")
investigation.studies.append(hcm)
hcm.identifier = "HCM"
hcm.title = "Human Challenge Colonisation"
hcm.description = """The Human Challenge study investigates the effect of the Bordatela pertussis (whooping cough)
inoculation on healthy individuals"""

evi_van_schuppen = Person(first_name="Evi", last_name="van Schuppen", affiliation="Radboud UMC")
guy_berbers = Person(first_name="Guy", last_name="Berbers", affiliation="RIVM, the Netherlands")
alex_barkoff = Person(first_name="Alex", last_name="Barkoff", affiliation="University of Turku")
pieter_van_gageldonk = Person(first_name="Pieter", last_name="van Gageldonk", affiliation="RIVM, the Netherlands")
alison_hill = Person(first_name="Alison", last_name="Hill", affiliation="University of Southampton")

hcm.contacts.extend([alison_hill, evi_van_schuppen, guy_berbers])
bert.contacts.extend([evi_van_schuppen, guy_berbers, alex_barkoff, pieter_van_gageldonk])

serum = Source(name='serum')
mlf = Source(name='nasal mucosal lining fluid')
unknown_src = Source(name="unknown")

bert.sources.extend([serum, mlf])
hcm.sources.extend([serum, mlf])

ncbi_taxon = OntologySource(name='NCBITaxon', description="NCBI Taxonomy")
human_characteristic= Characteristic(category=OntologyAnnotation(term="Organism"),
                                     value=OntologyAnnotation(term="Homo Sapiens", term_source=ncbi_taxon,
                                                              term_accession="http://purl.bioontology.org/ontology/NCBITAXON/9606"))

unknown_collection_process = Process(name="unknown")

bert_mlf_protocol = Protocol(name="collection of nasal mucosal lining fluid",
                             protocol_type=OntologyAnnotation(term="collect_mlf"))
bert.protocols.append(bert_mlf_protocol)
bert_mlf_process = Process(executes_protocol=bert_mlf_protocol)
bert_mlf_process.inputs.append(mlf)
bert.process_sequence.append(bert_mlf_process)

bert_serum_protocol = Protocol(name="collection of serum",
                               protocol_type=OntologyAnnotation(term="collect_serum"))
bert.protocols.append(bert_serum_protocol)
bert_serum_process = Process(executes_protocol=bert_serum_protocol)
bert_serum_process.inputs.append(serum)
bert.process_sequence.append(bert_serum_process)

hcm_mlf_protocol = Protocol(name="collection of nasal mucosal lining fluid",
                            protocol_type=OntologyAnnotation(term="collect_mlf"))
hcm.protocols.append(hcm_mlf_protocol)
hcm_mlf_process = Process(executes_protocol=hcm_mlf_protocol)
hcm_mlf_process.inputs.append(mlf)
hcm.process_sequence.append(hcm_mlf_process)

hcm_serum_protocol = Protocol(name="collection of serum",
                              protocol_type=OntologyAnnotation(term="collect_serum"))
hcm.protocols.append(hcm_serum_protocol)
hcm_serum_process = Process(executes_protocol=hcm_serum_protocol)
hcm_serum_process.inputs.append(serum)
hcm.process_sequence.append(hcm_serum_process)

extraction_protocol = Protocol(name='extraction', protocol_type=OntologyAnnotation(term="material extraction"))
bert.protocols.append(extraction_protocol)
hcm.protocols.append(extraction_protocol)

mia_protocol = Protocol(name='multiplex immuno assay', protocol_type=OntologyAnnotation(term="mia"))
bert.protocols.append(mia_protocol)
hcm.protocols.append(mia_protocol)

isatab.dump(isa_obj=investigation, output_path=final_dir)
```

I get this error:

```
isatab.py(_all_end_to_end_paths:1152) >> Found 0 paths!
Traceback (most recent call last):
  File "test.py", line 85, in <module>
    isatab.dump(isa_obj=investigation, output_path="test/")
  File "/usr/local/lib/python3.8/dist-packages/isatools/isatab.py", line 1047, in dump
    write_study_table_files(investigation, output_path)
  File "/usr/local/lib/python3.8/dist-packages/isatools/isatab.py", line 1188, in write_study_table_files
    for node in _longest_path_and_attrs(paths):
TypeError: 'NoneType' object is not iterable
```

**Comment by Zigur** [comment]
Hi @cbaakman, if I understand your case study your "collection of serum" process should take a Subject source as an input and a serum sample as an output. Something along these lines:

```
ncbi_taxon = OntologySource(name='NCBITaxon', description="NCBI Taxonomy")
human_characteristic= Characteristic(category=OntologyAnnotation(term="Organism"),
                                     value=OntologyAnnotation(term="Homo Sapiens", term_source=ncbi_taxon,
                                                              term_accession="http://purl.bioontology.org/ontology/NCBITAXON/9606"))
subject = Source(name='human individual', characteristics=[human_characteristic]) 
serum = Sample(name='serum')
mlf = Sample(name='nasal mucosal lining fluid')
```

And then in the process declaration:

```
hcm_mlf_protocol = Protocol(name="collection_of_nasal_mucosal_lining_fluid_HCM",
                            protocol_type=OntologyAnnotation(term="collect_mlf"))
hcm.protocols.append(hcm_mlf_protocol)
hcm_mlf_process = Process(executes_protocol=hcm_mlf_protocol)
hcm_mlf_process.inputs.append(subject)
hcm_mlf_process.outputs.append(mlf)
hcm.process_sequence.append(hcm_mlf_process)
```

And similarly for the other processes. If you do not provide inputs and outputs to a process the graph will be broken, hence the error. These docs could provide some help: https://isatools.readthedocs.io/en/latest/creationtutorial.html

**Comment by cbaakman** [comment]
OK @Zigur, thanks! I guess this could explain it. However, I do think that the library should output a more informative error than just "'NoneType' object is not iterable". How about something like: process x has no input.

**Comment by Zigur** [comment]
Yes, some of the error messages are a bit obscure and need some review. Thanks for the feedback and let us know if you've solved your issue

**Comment by cbaakman** [comment]
I'm now getting the following error:

```
  File "finalize_mia.py", line 452, in <module>
    isatab.dump(isa_obj=investigation, output_path=final_dir)
  File "/usr/local/lib/python3.8/dist-packages/isatools/isatab.py", line 1047, in dump
    write_study_table_files(investigation, output_path)
  File "/usr/local/lib/python3.8/dist-packages/isatools/isatab.py", line 1259, in write_study_table_files
    df_dict[olabel][-1] = node.executes_protocol.name
KeyError: 'Protocol REF.collection of serum'
```

I guess that's another hole in the gap that I need to fill?

**Comment by Zigur** [comment]
Hi, @cbaakman, you must provide the same name to all sample collection protocols in one study otherwise the serialization to ISA-tab will fail (conflicting names to the same column). You can indeed use one single protocol for all the sampling step in one study.
I am not sure if there are other options, maybe @proccaserra knows about them

See this notebook, for a solution that should fix your code: https://github.com/Zigur/isa-create-notebook/blob/dev/notebooks/example-issue-364.ipynb

**Comment by cbaakman** [comment]
Thanks! I'll look into this..

**Comment by proccaserra** [comment]
@cbaakman , @Zigur is correct about this assessment. This is not necessarily the ideal behaviour, i.e. that different protocols with the same protocol.type should be allowed to have distinct names. I tried it and it also fails at serialization.
 We'll see if we can amend the current behaviour. Thx for reporting.

**Comment by cbaakman** [comment]
I've made sure that different protocols had different names and I tied all the processes, protols, samples and sources togther.
I'm now no longer getting errors, so I can continue on doing the tutorial. Many thanks!
