### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by erlefloch** [ISA-tools/isa-api#476]
FYI: seen at BioHackathon with @proccaserra 
```
erwan@computer:~/Code/plant-brapi-to-isa$ sudo docker run -it -v /home/erwan/Code/plant-brapi-to-isa/outputdir:/outputdir brapi2isa -t aHR0cHM6Ly9kb2kub3JnLzEwLjE1NDU0L0lBU1NUTg%3D%3D -e https://urgi.versailles.inra.fr/faidare/brapi/v1/
[sudo] password for erwan: 
Traceback (most recent call last):
  File "/brapi_to_isa.py", line 12, in <module>
    from isatools.convert import isatab2json
  File "/usr/local/lib/python3.7/site-packages/isatools/__init__.py", line 20, in <module>
    from isatools.convert import (
  File "/usr/local/lib/python3.7/site-packages/isatools/convert/isatab2sra.py", line 9, in <module>
    from isatools.convert import isatab2json, json2sra
  File "/usr/local/lib/python3.7/site-packages/isatools/convert/json2sra.py", line 5, in <module>
    from isatools import isajson, sra
  File "/usr/local/lib/python3.7/site-packages/isatools/sra.py", line 17, in <module>
    import jinja2
  File "/usr/local/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)
```

**Comment by erlefloch** [comment]
I added `markupsafe==2.0.1` in my requirements.txt file to fix this.
see https://github.com/elixir-europe/plant-brapi-to-isa/pull/74

**Comment by bedroesb** [comment]
had to do the same thing!

**Comment by erlefloch** [comment]
I realised the pull request was merged, so I can close this issue right ? @bedroesb

**Comment by bedroesb** [comment]
@erlefloch but is it fixed on the isa-tools side? or do you mean a PR on this repository?
