### ISSUE TITLE
0.13.0 installation error

### ISSUE THREAD

**Issue by jundahuang9123** [ISA-tools/isa-api#487]
When pulled from master branch and install the 0.13.0 version. I encounter the following issue:

(isa) (venv) PS D:\CMBI_work\Projects\isa-api> python setup.py install
D:\CMBI_work\Projects\isa-api\venv\lib\site-packages\setuptools\dist.py:484: UserWarning: Normalizing '0.13.0-rc.2' to '0.13.0rc2'
  warnings.warn(tmpl.format(**locals()))
running install
running bdist_egg
running egg_info
writing isatools.egg-info\PKG-INFO
writing dependency_links to isatools.egg-info\dependency_links.txt
writing requirements to isatools.egg-info\requires.txt
writing top-level names to isatools.egg-info\top_level.txt
error: package directory 'isatools\errors' does not exist

When I look into the repository I indeed cannot find the isatools.errors directory. Simply remove the line 23 of setup.py, I could finish the installation. However, when using the package, there are following errors:

Traceback (most recent call last):
  File "D:\CMBI_work\Projects\TWOCdemonstrator\tools\Su_2020_prepare_ISA_metadata\isa-to-rdfs.py", line 10, in <module>
    from isatools import isatab
  File "D:\CMBI_work\Projects\isa-api\venv\lib\site-packages\isatools-0.13.0rc2-py3.10.egg\isatools\__init__.py", line 20, in <module>
    from isatools.convert import (
  File "D:\CMBI_work\Projects\isa-api\venv\lib\site-packages\isatools-0.13.0rc2-py3.10.egg\isatools\convert\isatab2cedar.py", line 14, in <module>
    from isatools.io import isatab_parser
  File "D:\CMBI_work\Projects\isa-api\venv\lib\site-packages\isatools-0.13.0rc2-py3.10.egg\isatools\io\isatab_parser.py", line 38, in <module>
    from isatools import isatab
  File "D:\CMBI_work\Projects\isa-api\venv\lib\site-packages\isatools-0.13.0rc2-py3.10.egg\isatools\isatab\__init__.py", line 1, in <module>
    from isatools.isatab.dump import (
ModuleNotFoundError: No module named 'isatools.isatab.dump'

**Comment by bedroesb** [comment]
@jundahuang9123 I encountered the same issues, and solved the first one in the same way. The second one I was also not able to solve. @terazus do you have plans on finishing off version 13 and fixing the `isatools.isatab.dump` problem?

**Comment by jundahuang9123** [comment]
@bedroesb, the second problem @terazus has pointed out that I have the virtual environment installed at a different directory from my work directory.

**Comment by bedroesb** [comment]
it is maybe worthed calling it v1.0.0 😉
